"""empty message

Revision ID: 05b920ef76be
Revises: 4a441be514a1
Create Date: 2022-11-08 22:19:54.902295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05b920ef76be'
down_revision = '4a441be514a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flight', sa.Column('depart_day', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'flight', 'week', ['depart_day'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'flight', type_='foreignkey')
    op.drop_column('flight', 'depart_day')
    # ### end Alembic commands ###
