"""empty message

Revision ID: 1e859f7efae1
Revises: b6f7ccac47e7
Create Date: 2022-11-16 15:52:14.638102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e859f7efae1'
down_revision = 'b6f7ccac47e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'flight', 'week', ['depart_day'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'flight', type_='foreignkey')
    # ### end Alembic commands ###
