"""empty message

Revision ID: 449f594415ce
Revises: 05b920ef76be
Create Date: 2022-11-08 22:44:19.754814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '449f594415ce'
down_revision = '05b920ef76be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flight_day')
    with op.batch_alter_table('flight', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'week', ['depart_day'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flight', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.create_table('flight_day',
    sa.Column('flight_id', sa.INTEGER(), nullable=True),
    sa.Column('weed_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['flight_id'], ['flight.id'], ),
    sa.ForeignKeyConstraint(['weed_id'], ['week.id'], )
    )
    # ### end Alembic commands ###
