"""add email column to user table

Revision ID: 6d8a4924804c
Revises: 162f260cc5f3
Create Date: 2022-12-02 15:35:22.708606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d8a4924804c'
down_revision = '162f260cc5f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.alter_column('booking_date',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint("unique_email", ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint("unique_email", type_='unique')
        batch_op.drop_column('email')

    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.alter_column('booking_date',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
