"""cascade delete

Revision ID: 9755b6b2706b
Revises: fc83da2d259f
Create Date: 2022-11-17 14:46:29.308256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9755b6b2706b'
down_revision = 'fc83da2d259f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('flight', schema=None) as batch_op:
    #     batch_op.create_foreign_key("depart_day", 'week', ['depart_day'], ['id'])

    with op.batch_alter_table('ticket_passenger', schema=None) as batch_op:
        batch_op.drop_constraint("drop_foreign_key", type_='foreignkey')
        batch_op.drop_constraint("drop_foreign_key", type_='foreignkey')
        batch_op.create_foreign_key("passenger_id", 'passenger', ['passenger_id'], ['id'], ondelete='cascade')
        batch_op.create_foreign_key("ticket_id", 'ticket', ['ticket_id'], ['id'], ondelete='cascade')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_passenger', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'passenger', ['passenger_id'], ['id'])
        batch_op.create_foreign_key(None, 'ticket', ['ticket_id'], ['id'])

    with op.batch_alter_table('flight', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
