"""empty message

Revision ID: b6f7ccac47e7
Revises: 4a309c2404c3
Create Date: 2022-11-16 15:51:16.681733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6f7ccac47e7'
down_revision = '4a309c2404c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket_passenger')
    op.drop_table('ticket')
    op.drop_table('passenger')
    op.create_foreign_key(None, 'flight', 'week', ['depart_day'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'flight', type_='foreignkey')
    op.create_table('passenger',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('gender', sa.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticket',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('flight_id', sa.INTEGER(), nullable=True),
    sa.Column('ref_no', sa.VARCHAR(length=6), nullable=False),
    sa.Column('flight_ddate', sa.TIME(), nullable=True),
    sa.Column('flight_adate', sa.TIME(), nullable=True),
    sa.Column('flight_fare', sa.FLOAT(), nullable=True),
    sa.Column('other_charges', sa.FLOAT(), nullable=True),
    sa.Column('total_fare', sa.FLOAT(), nullable=True),
    sa.Column('seat_class', sa.VARCHAR(length=20), nullable=False),
    sa.Column('booking_date', sa.TIME(), nullable=False),
    sa.Column('mobile', sa.VARCHAR(length=20), nullable=False),
    sa.Column('email', sa.VARCHAR(length=45), nullable=False),
    sa.Column('status', sa.VARCHAR(length=45), nullable=False),
    sa.ForeignKeyConstraint(['flight_id'], ['flight.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ref_no')
    )
    op.create_table('ticket_passenger',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('ticket_id', sa.INTEGER(), nullable=True),
    sa.Column('passenger_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['passenger_id'], ['passenger.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
