"""empty message

Revision ID: b80383e45d0d
Revises: 1e859f7efae1
Create Date: 2022-11-16 16:39:09.681568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b80383e45d0d'
down_revision = '1e859f7efae1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'flight', 'week', ['depart_day'], ['id'])
    op.alter_column('ticket', 'flight_ddate',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('ticket', 'flight_adate',
               existing_type=sa.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ticket', 'flight_adate',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('ticket', 'flight_ddate',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.drop_constraint(None, 'flight', type_='foreignkey')
    # ### end Alembic commands ###
