"""empty message

Revision ID: fc83da2d259f
Revises: b80383e45d0d
Create Date: 2022-11-16 16:42:48.047663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc83da2d259f'
down_revision = 'b80383e45d0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flight', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'week', ['depart_day'], ['id'])

    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.alter_column('flight_ddate',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('flight_adate',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.alter_column('flight_adate',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('flight_ddate',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('flight', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
